name: Update External Payload Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"  # Co 24 godzin

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout main repo
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      ###############################################################
      # CHECK IF FOLDER EXISTS, IF NOT â€” CREATE IT
      ###############################################################
      - name: Ensure Payload Repositories exists
        run: |
          if [ ! -d "Payload Repositories" ]; then
            echo "Create directory Payload Repositories"
            mkdir -p "Payload Repositories"
          else
            echo "Directory 'Payload Repositories' already exists!"
          fi

      ###############################################################
      # LIST OF REPOSITORIES TO FETCH
      ###############################################################
      - name: Set repository list
        id: repos
        run: |
          echo "repos=elder-plinius/CL4R1T4S liu00222/Open-Prompt-Injection" >> "$GITHUB_OUTPUT"

      ###############################################################
      # FETCH DATA
      ###############################################################
      - name: Download repositories
        run: |
          for repo in ${{ steps.repos.outputs.repos }}; do
            name=$(basename $repo)
            echo "Fetch repository: $repo"
            rm -rf "Payload Repositories/$name"
            git clone --depth 1 https://github.com/$repo.git "Payload Repositories/$name"
          done
